feat: add refres_token mechanism -- 21 (#2)
Co-authored-by: monkeydioude <duris.julien@gmail.com>

diff --git a/scripts/git/pre-push b/scripts/git/pre-push
--- a/scripts/git/pre-push
+++ b/scripts/git/pre-push
@@ -1,4 +1,14 @@
 #!/bin/sh
+
+echo "🔍 Running leaks check before commit..."
+make gitleaks
+STATUS=$?
+
+if [ $STATUS -ne 0 ]; then
+  echo "❌ Leaks check failed. Commit aborted."
+  exit 1
+fi
+
 # Check for added fmt.Println or fmt.Printf in the staged changes
 
 # Get the list of staged Go files
